[package]
name = "day13_transparent_origami"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent-of-code-ocr = "0.1.1"
exrunner = { path = "../exrunner" }
regex = "1.8.3"
